In [35]:

from sklearn.datasets import fetch_openml
import numpy as np


In [20]:
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [21]:
X, y = mnist['data'], mnist['target']
X.shape, y.shape

((70000, 784), (70000,))

In [36]:
import matplotlib as mpl
import matplotlib.pyplot as plt

# # some_digit = digits['data'][0]
# some_digit_image = some_digit.reshape(28, 28)
# plt.imshow(some_digit_image, cmap=mpl.cm.binary)
# plt.axis("off")

# plt.show()

In [37]:
y[0]

5

In [38]:
y = y.astype(np.uint8)

In [39]:
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [40]:
y_train_5 = (y_train == 5)
y_test_5 = (y_test == 5)

In [41]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_5)

SGDClassifier(random_state=42)

In [42]:
# sgd_clf.predict([some_digit])

In [49]:
# # cross-validation from scratch (amlost)

# from sklearn.model_selection import StratifiedKFold
# from sklearn.base import clone

# skfolds = StratifiedKFold(n_splits=3)

# for train_index, test_index in skfolds.split(X_train, y_train_5):
#     clone_clf = clone(sgd_clf)
#     X_train_folds = X_train[train_index]
#     y_train_folds = y_train_folds[train_index]
#     X_test_fold = X_train[test_index]
#     y_test_fold = y_train_5[test_index]

#     clone_clf.fit(X_train_folds, y_train_folds)
#     y_pred = clone_clf.predict(X_test_fold, y_test_fold)
#     n_correct = sum(y_pred == y_test_fold)
#     print(n_correct/(len(y_test_fold)))



In [50]:
from sklearn.model_selection import cross_val_score 

cross_val_score(sgd_clf, X_train, y_train_5, cv=3, scoring="accuracy")

array([0.95035, 0.96035, 0.9604 ])

In [51]:
from sklearn.base import BaseEstimator 

class Never5Classifier(BaseEstimator):
    def fit(self, X, y=None):
        return self
    def predict(self, X):
        return np.zeros((len(X), 1), dtype=bool)

In [52]:
never_5_clf = Never5Classifier()
cross_val_score(never_5_clf, X_train, y_train_5, cv=3, scoring="accuracy")

array([0.91125, 0.90855, 0.90915])

In [53]:
# because BaseEstimator and SGDClassifier both give approx. same accuracy
# on classifying 5 and not 5, it says nothing about the model, because 10% of the dataset is 5
# so you if you guess image is not 5, you will be (100%-10%) = 90% correct 

In [54]:
from sklearn.model_selection import cross_val_predict 

y_train_pred = cross_val_predict(sgd_clf, X_train, y_train_5, cv=3)

In [56]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_train_5, y_train_pred)

# ACTUAL CLASS        TN  FP
# PREDICTED CLASS     FN  TP

array([[53892,   687],
       [ 1891,  3530]], dtype=int64)

In [58]:
y_train_perfect_predictions = y_train_5 # pretend we reached perfection
confusion_matrix(y_train_5, y_train_perfect_predictions)

array([[54579,     0],
       [    0,  5421]], dtype=int64)